name: 'Dotenv Flow Action'
description: 'Load variables from .env* files'
branding:
  icon: play
  color: green
inputs:
  path:  # id of input
    description: 'specify a path to .env* files directory'
    required: true
    default: './'
  log-variables:
    description: 'whether to log the variables to output or not'
    required: false
    default: 'false'
  mask-variables:
    description: 'whether to mask the variables as secrets or not'
    required: false
    default: 'false'
outputs:
  generic: # output will be available to future steps 
    description: 'This command will have generic output variables based on .env'
runs:
  using: 'node16'
  main: 'dist/index.js'